Library/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('author.urls' , namespace='Library')),
    
    path('authors/', include('author.urls' , namespace='Library')),
    path('books/', include('book.urls' , namespace='book')),
    
]

book/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
import re

app_name = 'book'

urlpatterns = [
    path('book/', views.index),
    
    path('', views.AllBooks, name='AllBooks'),
    path('<int:id>/', views.ReadBook, name='ReadBook'),
    path('<int:id>/edit', views.EditBook, name='EditBook'),

    path('create/', views.createBook, name='createBook'),

    path('<int:id>/delete/', views.DelBook, name='DelBook'),

    path('searchBook/', views.searchBook, name='searchBook'),

    ]

book/models.py
from django.db import models
from django.contrib.auth.models import User # can be removed
from django.utils import timezone
from author.models import Author
# Create your models here.

BOOK_STATUS_CHOICES = (
        ('Published','Published'), 
        ('Withdrawn','Withdrawn'), 
        ('Draft','Draft'),
    )

class Book(models.Model):
    book_author = models.ForeignKey(Author, on_delete = models.CASCADE , related_name='AuthorBooks')
    book_title = models.CharField(max_length=50)
    book_category = models.CharField(max_length=20)
    book_pages_num = models.IntegerField()
    book_date_of_publish = models.DateTimeField(default=timezone.now)
    book_status = models.CharField( 
        max_length = 20, 
        choices = BOOK_STATUS_CHOICES, 
        default = 'Published'
        )
    


    def __str__(self):
        return self.book_title

   

book/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['book_title','book_category','book_pages_num','book_date_of_publish','book_status']


class BookSearch(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['book_title']

book/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.http import HttpResponse

from .models import Book

from .forms import BookForm , BookSearch


# Create your views here.
def index(request):
    return render(request,"index.html",{"key":"Mahmoud Amr"})


def searchBook(request):
    if request.method == 'POST' :
        searchFieldValue = BookSearch(request.POST)
        if searchFieldValue.is_valid() :
            name = searchFieldValue.cleaned_data['book_title']
            if name != '' and name is not None :
                try:
                    BookObj = get_object_or_404(Book , book_title=name)
                    context = {
                        'ABook' : BookObj ,
                    }
                    return render(request , 'readOnee.html' , context)
                    
                except :
                    return render(request,"indexx.html", {"key":"Sorry..Book cannot be found, Try again"})           
            else:
                return render(request,"indexx.html", {"key":""}) # if index.html , it will redirect to index.html in author

    else :
        form = BookSearch()
        context = {
            'form' : form ,
        }
        return render(request,"indexx.html", context)

############################################################################################333


# Read/Get All Books for the specific Author
def AllBooks(request):
    allBooks = Book.objects.all()

    context = {
        'allBooks' : allBooks ,
    }
    return render(request , 'readAll.html' , context)

# Read/Get specific Book
def ReadBook(request, id):
    ABook = get_object_or_404(Book , id=id)
    
    context = {
        'ABook' : ABook ,
    }
    return render(request, 'readOne.html' , context)


# Edit specific Book
def EditBook(request, id):
    ABook = get_object_or_404(Book , id=id)
    if request.method == 'POST' :
        form = BookForm(request.POST , instance=ABook)
        if form.is_valid():
            remainFieldsForm = form.save(commit=False)
            remainFieldsForm.book_author = request.user
            remainFieldsForm.save()
            return redirect('/')
        else:
            return redirect('/')

    else :
        form = BookForm(instance=ABook)
    
    context = {
        'form' : form ,
    }

    return render(request, 'edit.html', context)     


# Create/Insert Book Action/View

def createBook(request):
    if request.method == 'POST' :
        form = BookForm(request.POST)
        if form.is_valid():
            remainFieldsForm = form.save(commit=False)
            remainFieldsForm.book_author = request.user
            remainFieldsForm.save()
            return redirect('/')
        else:
            return redirect('/')


    else :
        form = BookForm()
    
    context = {
        'form' : form ,
    }

    return render(request, 'create.html', context) 


# Delete a Book
def DelBook(request, id):
    Book.objects.filter(id=id).delete()
    return redirect('/')
    

book/templates/create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">
        <title>Creating New Book</title>
        <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    </head>
    <body>

        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">End Publishing</button>
        </form>

    </body>
</html>

book/templates/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">
        <title>Edit Author</title>
        <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    </head>
    <body>

        <form method="post" target="views.AllBooks">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Finish Editing Book</button>
        </form>

    </body>
</html>

book/templates/indexx.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">
        <title>Book Search Page</title>
        <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    </head>
    <body>

        <h1>Enter the Book Title You Wish to Search , {{ key }}</h1>

        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Go Search</button>
        </form>

    </body>
</html>

book/templates/readAll.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">
        <title>All Books Details</title>
        <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    </head>
    <body>

        <a href="{% url 'Library:createBook' %}">Create New Book</a>

        {% for book in allBooks %}

        <h3><a href="{% url 'Library:ReadBook' book.id %}">{{ book.book_title }}</a></h3>

        {% endfor %}

    </body>
</html>

book/templates/readOnee.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">
        <title>Book Details</title>
        <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    </head>
    <body>

        <h2>{{ ABook.book_title }}</h2>
        <h2>{{ ABook.category }}</h2>
        <h2>{{ ABook.book_pages_num }}</h2>
        <h2>{{ ABook.book_date_of_publish }}</h2> 
        <h2>{{ ABook.book_status }}</h2>
        

        <h3><a href="{% url 'Library:EditBook' ABook.id %}">Edit This Book</a></h3>
        
       <h3><a href="{% url 'Library:DelBook' ABook.id %}">Delete This Book</a></h3>



    </body>
</html>