Library/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('author.urls' , namespace='Library')),
    
    path('authors/', include('author.urls' , namespace='Library')),
    path('books/', include('book.urls' , namespace='book')),
    
]

author/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
import re

from book.views import searchBook

app_name = 'author'

urlpatterns = [
    path('author/', views.index),

    path('', views.index , name='SiteIndex'),
    
    path('AllAuthors/', views.AllAuthors, name='AllAuthors'),
    path('<int:id>/', views.ReadAuthor, name='ReadAuthor'),
    path('<int:id>/edit', views.EditAuthor, name='EditAuthor'),

    path('create/', views.createAuthor, name='createAuthor'),

    path('<int:id>/delete/', views.DelAuthor, name='DelAuthor'),


    #path('searchBook/' , searchBook , name='searchBook') ,


    ]

book/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
import re

app_name = 'book'

urlpatterns = [
    path('book/', views.index),
    
    path('', views.AllBooks, name='AllBooks'),
    path('<int:id>/', views.ReadBook, name='ReadBook'),
    path('<int:id>/edit', views.EditBook, name='EditBook'),

    path('create/', views.createBook, name='createBook'),

    path('<int:id>/delete/', views.DelBook, name='DelBook'),

    path('searchBook/', views.searchBook, name='searchBook'),

    ]

author/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Author(models.Model):
    #author_user = models.OneToOneField(User, on_delete=models.CASCADE, default='')
    author_name = models.CharField(unique=True , max_length=20)
    author_age = models.IntegerField()
    author_nationality = models.CharField(max_length=20)
    author_phone_number = models.IntegerField()


    def __str__(self):
        return self.author_name

        

author/forms.py
from django import forms
from .models import Author

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['author_name','author_age','author_nationality','author_phone_number']


class AuthorSearch(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['author_name']

author/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.http import HttpResponse

from .models import Author

from book.models import Book

from .forms import AuthorForm , AuthorSearch


# Create your views here.
def index(request):
    if request.method == 'POST' :
        searchFieldValue = AuthorSearch(request.POST)
        #name = searchFieldValue.save(commit=False).author_name
        if searchFieldValue.is_valid() :
            name = searchFieldValue.cleaned_data['author_name']
            # name = request.POST.get('author_input') # if there is a textfield created in html 
            if name != '' and name is not None :
                #AuthObj = Author.objects.get(author_name=name)
                try:
                    AuthObj = get_object_or_404(Author , author_name=name)
                    context = {
                        'AnAuth' : AuthObj ,
                    }
                    return render(request , 'readOne.html' , context)
                    
                except :
                    return render(request,"index.html", {"key":"Sorry..Author cannot be found, Try again"})           
            else:
                return render(request,"index.html", {"key":""})

    else :
        form = AuthorSearch()
        context = {
            'form' : form ,
        }
        return render(request,"index.html", context)


'''
# Create your views here.
def index(request):

    form = AuthorSearch()
    context = {
        'form' : form ,
    }
    return render(request,"index.html", context)
'''

# Search for Author
'''
def searchAuthor(request , authName):
    AnAuth = Author.objects.get(author_name=authName)
    if AnAuth != null :
        context = {
            'AnAuth' : AnAuth ,
        }
        return render(request , 'readOne.html' , context)
    
    else :
        return render(request,"index.html", {"key":"Sorry..Author cannot be found, Try again"})
'''

# Search for Author # Became not used

def searchAuthor(request , authName):
    AnAuth = Author.objects.get(author_name=authName)
    if AnAuth != null :
        form = AuthorSearch(instance=AnAuth)
        context = {
            'form' : form ,
        }
        return render(request , 'readOne.html' , context)
    
    else :
        return render(request,"index.html", {"key":"Sorry..Author cannot be found, Try again"})

##########################################################################################





##########################################################################################
# Read/Get All Authors for the loged in user
def AllAuthors(request):
    allAuth = Author.objects.all()

    context = {
        'allAuth' : allAuth ,
    }
    return render(request , 'readAll.html' , context)

# Read/Get specific Author
def ReadAuthor(request, id):
   # AnAuth = Author.objects.get(id=id)   # as we want to show 404 error if id isn't found, we will use the next line
    AnAuth = get_object_or_404(Author , id=id)
    
    context = {
        'AnAuth' : AnAuth ,
    }
    return render(request, 'readOne.html' , context)


# Edit specific Author
def EditAuthor(request, id):
    AnAuth = get_object_or_404(Author , id=id)
    if request.method == 'POST' :
        form = AuthorForm(request.POST , instance=AnAuth)
        if form.is_valid():
            remainFieldsForm = form.save(commit=False)
            remainFieldsForm.author_user = request.user
            remainFieldsForm.save()
            return redirect('/')
        else:
            return redirect('/')

    else :
        form = AuthorForm(instance=AnAuth)
    
    context = {
        'form' : form ,
    }

    return render(request, 'edit.html', context)     


# Create/Insert Author Action/View

def createAuthor(request):
    if request.method == 'POST' :
        form = AuthorForm(request.POST)
        if form.is_valid():
            remainFieldsForm = form.save(commit=False)
            remainFieldsForm.author_user = request.user
            remainFieldsForm.save()
            return redirect('/')
        else:
            return redirect('/')


    else :
        form = AuthorForm()
    
    context = {
        'form' : form ,
    }

    return render(request, 'create.html', context) 


# Delete an Author
def DelAuthor(request, id):
    Author.objects.filter(id=id).delete()
    return redirect('/')

    #instance = SomeModel.objects.get(id=id)
    #instance.delete()

author/templates/create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">
        <title>Creating New Author</title>
        <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    </head>
    <body>

        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Ending Creation</button>
        </form>

    </body>
</html>

author/templates/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">
        <title>Edit Author</title>
        <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    </head>
    <body>

        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Finish Editing</button>
        </form>

    </body>
</html>

author/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">
        <title>Welcome To Our Online Library</title>
        <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    </head>
    <body>

        <h1>Hello Django, {{ key }}</h1>

        
        
       <h3><a href="{% url 'Library:AllAuthors' %}">Display Authors in Our Library</a></h3>

       <h3><a href="{% url 'book:searchBook' %}">Search for Books in Our Library</a></h3>

       <h4>Search for Authors or Books You Want ..</h4>

       <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Go Search</button>
        </form>

    </body>
</html>

author/templates/readAll.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">
        <title>All Authors Details</title>
        <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    </head>
    <body>

        <a href="{% url 'Library:createAuthor' %}">Create New Author</a>

        {% for auth in allAuth %}

        <h3><a href="{% url 'Library:ReadAuthor' auth.id %}">{{ auth.author_name }}</a></h3>

        {% endfor %}

    </body>
</html>

author/templates/readOne.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">
        <title>Author Details</title>
        <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    </head>
    <body>

        <h2>{{ AnAuth.author_name }}</h2>
        <h2>{{ AnAuth.author_age }}</h2>
        <h2>{{ AnAuth.author_nationality }}</h2>
        <h2>{{ AnAuth.author_phone_number }}</h2>
        

        <h3><a href="{% url 'Library:EditAuthor' AnAuth.id %}">Edit This Author</a></h3>
        
       <h3><a href="{% url 'Library:DelAuthor' AnAuth.id %}">Delete This Author</a></h3>



    </body>
</html>